# Generated by Django 4.2 on 2026-04-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
            ],
        ),
    ]
